src/Mission X/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace Mission_X.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/Mission X/Controllers/ThreePointController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace Mission_x.Controllers
{
    public class ThreePointController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Mission X/Controllers/TrigonometryController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;

namespace MissionX.Controllers
{
    public class TrigonometryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Mission X/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Mission X/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Mission X/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<table style="border-collapse: separate; border-spacing: 20px;">
    <tr>

        <td>
            <div class="demo-card-wide mdl-card mdl-shadow--4dp" id="trigcard">

                <div class="mdl-card__title" id="card1">
                    
                </div>

                <div class="mdl-card__supporting-text">
                    <h2 class="mdl-card__title-text">Trigonometry Problems</h2>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Mauris sagittis pellentesque lacus eleifend lacinia...
                </div>


                <div class="mdl-card__actions mdl-card--border">
                    <a asp-controller="Trigonometry" asp-action="Index" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                        Solve Problems
                    </a>
                </div>

            </div>

            

            <br />
            <br />
            <div id="p3" class="mdl-progress mdl-js-progress"><br />05% Complete </div>

            <div class="mdl-tooltip mdl-tooltip--large" for="trigcard">
                Solve Trignometry Problems
            </div>
        </td>

        <td>
            <div class="demo-card-wide mdl-card mdl-shadow--4dp" id="attcard">

                <div class="mdl-card__title" id="card2">
                    
                </div>

                <div class="mdl-card__supporting-text">
                    <h2 class="mdl-card__title-text">Simple Plan View </h2>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Mauris sagittis pellentesque lacus eleifend lacinia...
                </div>


                <div class="mdl-card__actions mdl-card--border">
                    <a asp-controller="Attitude" asp-action="Index" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                        Solve Problems
                    </a>
                </div>

            </div>

            <br />
            <br />
            <div id="p4" class="mdl-progress mdl-js-progress"> <br />15% Complete </div>

            <div class="mdl-tooltip mdl-tooltip--large" for="attcard">
                Simple Plan View Problems involving strike and dip
            </div>
        </td>


        <td>
            <div class="demo-card-wide mdl-card mdl-shadow--4dp" id="borehole">

                <div class="mdl-card__title" id="card3">
                   
                </div>

                <div class="mdl-card__supporting-text">
                    <h2 class="mdl-card__title-text">Bore Hole Problems</h2>
                    Bore hole problems or 3 - point problems invo
                </div>


                <div class="mdl-card__actions mdl-card--border">
                    <a asp-controller="ThreePoint" asp-action="Index" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                        Solve Problems
                    </a>
                </div>

            </div>
            <br />
            <br />

            <div id="p5" class="mdl-progress mdl-js-progress"><br /> 05% Complete </div>

            <div class="mdl-tooltip mdl-tooltip--large" for="borehole">
                Bore hole problems or 3 - point Problems
            </div>
        </td>

    </tr>
</table>

<br />
<br /><br />
<div class="panel panel-default">
    <div class="panel-heading"><h3>Total Project Progress</h3></div>
    
    <br />
   
    <div id="projectstatus" class="panel-body mdl-progress mdl-js-progress"><br /> 25% Complete </div>
    <br />
    <br />
</div>





                  